apiVersion: apps/v1
kind: Deployment
metadata:
  # deployment name
  name: node-deployment
  labels:
    app: node
    version: "2.0"
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: node
      version: "2.0"
  # pod template
  template:
    metadata:
      labels:
        app: node
        version: "2.0"
    spec:
      # pod contains 1 container
      containers:
      - name: node
        image: ca2acrx00193212.azurecr.io/fe-service-ca2:v2
        # container opens port 22137
        ports:
        - containerPort: 22137
          name: http
          protocol: TCP
