apiVersion: apps/v1
kind: Deployment
metadata:
  # deployment name
  name: node-deployment-v1
  labels:
    app: node
    deployment: green
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: node
      deployment: green
  # pod template
  template:
    metadata:
      labels:
        app: node
        deployment: green
    spec:
      # pod contains 1 container
      containers:
      - name: node
        image: ca2acrx00193212.azurecr.io/fe-service-ca2-prod:v2
        # container opens port 22137
        ports:
        - containerPort: 22137
          name: http
          protocol: TCP
