on:
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v1
      - run: |
          set -x
          docker version
          docker run hello-world
      - name: Set up Maven
        uses: thermofisher/setup-maven@v1.0.0
        with:
          maven-version: 3.8.2
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
      - run: java HelloWorldApp.java
