on:
  workflow_dispatch: 
    
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v1
      - run: |
          set -x
          docker version
          docker run hello-world
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2
      - run: mvn --version
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      - run: java --version
      - name: create war file
        run: |
          cd ./EAD_WS_CA1_2023
          mvn clean package
      - name: create a docker image of war file
        run: |
          cd ./EAD_WS_CA1_2023
          docker image build --tag=web-service-ca2:v1 -f ./EAD_WS_CA1_2023/
          docker tag web-service-ca2:v1 ca2acrx00193212.azurecr.io/web-service-ca2:v1
          
      - uses: azure/setup-kubectl@v2.0
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: push image to acr
        run: |
          docker push ca2acrx00193212.azurecr.io/web-service-ca2:v1
      - name: associate creds
        run: |
          az aks update -n AKSCluster -g ca2-resource-group --attach-acr ca2acrx00193212
          
      - name: kubeconf file generation
        run: |
          az aks get-credentials --resource-group ca2-resource-group --name AKSCluster
          
      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        
      - name: deploy image from acr to aks
        run: kubectl apply -f ./create-service-manifest.yaml
