on:
  workflow_dispatch:

jobs:
  statefulset-deployment-configure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-kubectl@v2.0
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: kubeconf file generation
        run: |
          az aks get-credentials --resource-group my-resource-group --name AKSCluster

      - name: Install kubectl
        uses: azure/setup-kubectl@v1

      - name: Initiate MongoDB Replica Set
        run: |
         kubectl run ubuntu --image=ubuntu:20.04 --restart=Never --namespace=prod -- bash -il <<EOF
         apt-get update && apt-get install -y mongodb-clients
         mongo --eval 'rs.initiate( { _id: "rs0", members:[{ _id: 0, host: "mongo-0.mongo:27017" }] });rs.add("mongo-1.mongo:27017");rs.add("mongo-2.mongo:27017");'
         EOF