on: 
  workflow_dispatch:
  
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         
         - uses: azure/setup-kubectl@v2.0
         - name: Log in with Azure
           uses: azure/login@v1
           with:
              creds: '${{ secrets.AZURE_CREDENTIALS }}'
              
         - name: associate creds
           run: az aks update -n AKSCluster -g ca2-resource-group --attach-acr ca2acrx00193212
           
         - name: kubeconf file generation
           run: az aks get-credentials --resource-group ca2-resource-group --name AKSCluster
           
         - name: Install kubectl
           uses: azure/setup-kubectl@v1

         - name: Configure kubectl
           run: |
            mkdir -p ~/.kube
            cp ${{ github.workspace }}/kubeconfig ~/.kube/config
           
         - name: deploy image from acr to aks
           run:  kubectl apply -f ./create-nodejs-service-manifest.yaml

            
            
            
