name: e2e deployment
on:
  workflow_dispatch:
  
env:
  DB_CONNECTION_STRING: '${{ secrets.DB_CONNECTION_STRING }}'

jobs:
  deploy-fe-service:
    runs-on: ubuntu-latest    
    steps:
      - name: checkout the repo    
        uses: actions/checkout@v2      
        
      - name: Set up node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '14'
          
      - name: run fe tests 
        run: |
          cd ./EAD_FE_CA1_2023
          npm install
          npm test
      
      - name: Upload test reports
        uses: actions/upload-artifact@v2
        with:
          name: coverage-reports
          path: ./EAD_FE_CA1_2023/coverage
          
      - name: SonarCloud Scan on FE Service code
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_HOST_URL: "https://sonarcloud.io"
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.javascript.lcov.reportPaths=./EAD_FE_CA1_2023/coverage/lcov.info
            -Dsonar.exclusions=./EAD_FE_CA1_2023/node_modules/**/*,coverage/**/*,**/*.java
            
      - name: Call Java sonar test Workflow
        uses: actions/workflow-dispatch@v2
        with:
          workflow: WebService scan
          ref: main
