on:
  workflow_dispatch:

jobs:
  blue-to-green:
    runs-on: ubuntu-latest
    steps:
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: associate creds
        run: |
          az aks update -n AKSCluster -g my-resource-group --attach-acr ca2acrx00193212

      - name: kubeconf file generation
        run: |
          az aks get-credentials --resource-group my-resource-group --name AKSCluster

      - name: Install kubectl
        uses: azure/setup-kubectl@v1

      - name: rout traffic to green
        run: |
          cd ./EAD_FE_CA1_2023
          kubectl apply -f service-version.yaml